---

- hosts: all
  become: true
  pre_tasks:

  - name: update repos cache (Debian)
    tags: always
    apt:
      update_cache: yes
    changed_when : false
    when: ansible_distribution == "Debian"

- hosts: all
  become: true
  roles:
    - base
            
- hosts: web_servers
  become: true
  roles:
    - web_servers
 
- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: files_servers
  become: true
  roles:
    - files_servers

- hosts: workstations
  become: true
  roles:
    - workstations
  

   
