- name: install apache2 and php packages for debian
  tags: apache,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  tags: apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin
  tags: apache,apache2
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution == "Debian"
  notify: restart_apache

- name: copy the default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
