- name: install apache2 and php packages for debian
  tags: apache,apache2,Debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: copy the default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: start apache service
  tags: apache, apache2
  service:
    name: apache2
    state: started
  when: ansible_distribution == "Debian"

- name: change e-mail address for admin
  tags: apache,apache2
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Debian"
  register: apache2

- name: restart apache2
  tags: apache,apache2
  service:
    name: apache2
    state: restarted
  when: apache2.changed
